---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: app-iac-automation
  annotations:
    crossplane.io/external-name: app-iac-automation
spec:
  deletionPolicy: Delete
  forProvider:
    tagging:
      tagSet:
        - key: pipeline
          value: tekton
        - key: squad
          value: iac
    acl: private
    locationConstraint: us-east-1
    serverSideEncryptionConfiguration:
      rules:
        - applyServerSideEncryptionByDefault:
            sseAlgorithm: AES256
    versioningConfiguration:
      status: Enabled
  providerConfigRef:
    name: provider-aws
---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: User
metadata:
  name: maicon-siqueira
  labels:
    example: "true"
spec:
  forProvider:
    tags:
      - key: k1
        value: v1
  providerConfigRef:
    name: provider-aws
